= Isc-Dhcp-Server : Configurer un serveur DHCP
:source-highlighter: highlightjs
:sectnums:
:toc:
:experimental:



Le DHCP (_Dynamtic Host Control Protocol_) permet d’attribuer automatiquement les adresses IP des ordinateurs clients. Ainsi l’attribution n’est plus manuelle et se fait de manière transparente pour l’utilisateur, on utilise le serveur DHCP dans un réseau local et notamment pour se connecter au routeur (votre box internet).

WARNING: Les interfaces réseaux de votre serveur doivent être configurées **obligatoirement** en adresses IP statiques

Premièrement, installez le paquet `isc-dhcp-server`.

----
# aptitude install isc-dhcp-server
----

Editez le fichier de configuration suivante : `/etc/dhcp/dhcpd.conf`
----
# nano /etc/dhcp/dhcpd.conf
----

Ajouter ici les lignes correspondantes à la configuration que vous souhaitez, par exemple :

[source,nginx]
----
### Changer ces lignes

# Nom de domaine pour le réseau local
option domain-name "security-helpzone.lan";

# Utilisation des DNS, si vous avez bind d'installé vous pouvez spécifier les IPs (comme moi), sinon utilisez les DNS de Google
option domain-name-servers 192.168.1.2, 192.168.1.3;

# Temps durant lequel les adresses ip locales seront assignées (en secondes)
default-lease-time 86400;
max-lease-time 604800;

### Il faut décommenter cette ligne
authoritative;

### Ajout de l'attribution
subnet 192.168.1.0 netmask 255.255.255.0 {
	# rang d'attribution (100 machines)
	range 192.168.1.100 192.168.1.200;

	# masque de sous-réseau
	option subnet-mask 255.255.255.0;

	# adresse ip du routeur
	option routers 192.168.1.254;
}
----

Une fois ceci fait, vérifier la configuration de votre fichier avec :

----
# /sbin/dhcpd -t
----

Indiquer l’interface sur laquelle les adresses IP seront attribuées.
----
# nano /etc/default/isc-dhcp-server
----

À la ligne : `INTERFACES= ""`, indquer la ou les interfaces (séparées par une virgule) à écouter.

Chez moi ce sera :
----
INTERFACES="eth0"
----

Redémarrer ensuite le serveur dhcp
----
# systemctl restart isc-dhcp-server
----

Votre serveur DHCP devrait être fonctionnel !

Pour tester si le dhcp fonctionne, utiliser la commande `dhclient`.
----
# dhclient eth0
----

## Faire une réservation

Il suffit la directive `host` dans la section `subnet` :

[source,nginx]
----
host client1 {
		hardware ethernet DD:GH:DF:E5:F7:D7;
		fixed-address 192.168.1.20;
}
----


## Vérifications

Si il y a des messages d'erreurs, regardez le fichier suivant :

----
# tail /var/log/syslog
----





## Logs

Les événements sont enregistrés par défaut dans `/var/log/syslog`. Pour qu'ils soient enregistrés dans un fichier de log dédié, par exemple `/var/log/dhcpd.log` :

  * Dans le fichier de conf `/etc/dhcp/dhcpd.conf`, ajoutez :
----
log-facility local7;
----

  * Créer le fichier `/var/log/dhcpd.log`.
----
# touch /var/log/dhcpd.log
----

  * Puis ajouter ceci dans le fichier /etc/rsyslog.d/50-default.conf :
----
local7.*          /var/log/dhcpd.log
----

  * Pour ne plus logguer dans syslog, dans `/etc/rsyslog.conf` modifier :
----
daemon.*            -/var/log/daemon.log
----
en
----
daemon.*;local7.none            -/var/log/daemon.log
----

  * et relancer les daemons syslog et isc-dhcp-server
----
service rsyslog restart
service isc-dhcp-server restart
----

## Baux (Leases)

Par défaut, le fichier `/var/lib/dhcp/dhcpd.leases` donne des informations sur les baux actuellement distribués par le serveur. On y retrouve des informations essentielles comme l'adresse IP distribuée à une adresse MAC, le nom de la machine qui a fait cette demande DHCP, l'heure de début et de fin du bail…

./var/lib/dhcp/dhcpd.leases
----
    lease 192.168.2.128 {
      starts 2 2012/07/31 20:24:28;
      ends 3 2012/08/01 01:24:28;
       ...
       hardware ethernet 01:11:5b:12:34:56;
       ...
       client-hostname "machine01";
    }
----

## Relais DHCP

Sur les réseaux de grande envergure, le réseau peut être segmenté. Ceci a notamment pour effet la réduction des trames de multi-diffusion, puisqu'elles ne sont pas routées. Le serveur DHCP n'est alors plus joignable par le client.

Dans ce cas, un relais DHCP peut être placé sur chaque segment réseau. L'agent relais écoute les requêtes des clients et les transfère au serveur DHCP. Cette fois-ci, le serveur peut être contacté, puisque l'agent relais établit la connexion via une connexion TCP/IP.

=== Configuration

Vous devrez changer la configuration par défaut en éditant le fichier `/etc/default/dhcpd-relay` :

----
# le serveur DHCP a relayer
SERVERS="192.168.1.1"
# Interface a écouter
INTERFACES="eth0 eth1"
----

Dans les interfaces, il doit y avoir l'interface pour communiquer avec le client, ainsi que l'interface pour communiquer avec le serveur DHCP.

Il faut également éditer le fichier `/etc/dhcp/dhcpd.conf` dans le serveur DHCP, et ajouter le réseau où se trouve le relais DHCP.

----
#Remplacez 192.168.2.0 par le réseau où se trouve le relais DHCP
subnet 192.168.2.0 netmask 255.255.255.0 {}
----


## Générer une demande DHCP

----
# nmap --script broadcast-dhcp-discover
Starting Nmap 7.70 ( https://nmap.org ) at 2020-01-14 17:43 CET
Pre-scan script results:
| broadcast-dhcp-discover:
|   Response 1 of 1:
|     IP Offered: 192.168.186.130
|     DHCP Message Type: DHCPOFFER
|     Server Identifier: 192.168.186.129
|     IP Address Lease Time: 5m00s
|     Subnet Mask: 255.255.255.0
|     Router: 192.168.186.254
|     Domain Name Server: 192.168.1.2, 192.168.1.3
|_    Domain Name: security-helpzone.lan
WARNING: No targets were specified, so 0 hosts scanned.
Nmap done: 0 IP addresses (0 hosts up) scanned in 1.54 seconds
----

## Snippet

----
##### Option générale par défaut #####

### RÉSEAU #####

## Nom du serveur DHCP
server-name "dhcp.manastria.fr";

## Mode autoritaire (autoritaire)
authoritative;

### DOMAINE ###

## Nom du domaine
option domain-name "manastria.fr";

## Adresse IP du serveur DNS
# A remplacer par l'IP du serveur DNS
option domain-name-servers XXX.XXX.XXX.XXX;

### TEMPS DE RENOUVÈLEMENT DES ADRESSES (en secondes) ###
default-lease-time 3600;
max-lease-time 7200;

### Sécurité ###

## refus(deny)/autorise(allow) les clients inconnus (refuse client inconnu)
allow unknown-clients;

## Use this to send dhcp log messages to a different log file (you also
## have to hack syslog.conf to complete the redirection).
log-facility local7;

##### RÉSEAUX #####
## déclaration sous réseau 192.168.1.*
subnet 192.168.1.0 netmask 255.255.255.0 {
  # Si vous voulez spécifier un domaine différent de celui par défaut :
  option domain-name "ubuntu-fr.lan";

  ## Serveurs DNS 
  option domain-name-servers 8.8.8.8, 1.1.1.1;

  ## routeur par défaut
  option routers 192.168.1.1;
        ## Plage d'attribution d'adresse
        # Ici débute à 1.10, 1.1 à 1.9 étant déjà prises.
  range 192.168.1.10 192.168.1.100;
  range 192.168.1.150 192.168.1.200;
  # évalue si l'adresse est déjà attribuée
  ping-check = 1;
}


#### Configuration des hôtes avec IP fixée ####
# hôte « FTP »
host ftp {
  hardware ethernet 00:0f:75:af:eb:44;
  fixed-address 192.168.1.2;
} 
# hôte « WEB »
host web {
  hardware ethernet 00:02:0d:31:d1:cc;
  fixed-address 192.168.1.3;
}


# Groupe séparé avec certains paramètres équivalents :
group {
  # Tout le groupe disposera d'un autre serveur DNS (dans ce cas "desktop" et "tv")
  options domain-name-servers 8.8.4.4;
  host desktop {
    hardware ethernet ab:cd:ef:11:22:33;
  }
  
  host tv {
    hardware ethernet 33:22:11:ef:cd:ab;
  }
}
----